apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-cm
data:
  MONGO_URL: 'mongodb://admin1:roboshop1@roboshop-prod.cluster-cmscnppwjzuf.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  MONGO_URL: 'mongodb://admin1:roboshop1@roboshop-prod.cluster-cmscnppwjzuf.us-east-1.docdb.amazonaws.com:27017/users?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'
  REDIS_HOST: redis-prod.roboshop.internal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm
data:
  REDIS_HOST: redis-prod.roboshop.internal
  CATALOGUE_HOST: catalogue-roboshop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-cm
data:
  DB_HOST: mysql-prod.roboshop.internal
  CART_ENDPOINT: cart-roboshop:8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-cm
data:
  CART_HOST: cart-roboshop
  USER_HOST: user-roboshop
  AMQP_HOST: rabbitmq-prod.roboshop.internal
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123
