## String need not to be quoted , But numbers should be in user inputs.
apiVersion: v1
kind: Pod
metadata:
  name: demo2
  labels:
    purpose: demo
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: demo3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: mongodb
      image: mongo
---
apiVersion: v1
kind: Pod
metadata:
  name: demo4
spec:
  containers:
    - name: centos
      image: centos:7
      command: [ "sleep", "10000" ]
      env:
        - name: URL
          value: www.example.com
        - name: DOMAIN
          value: example.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data:
  URL: www.example.com
  DOMAIN: example.com
  FULL_URL: "http://www.example.com"

---
apiVersion: v1
kind: Pod
metadata:
  name: demo5
spec:
  containers:
    - name: centos
      image: centos:7
      command: [ "sleep", "10000" ]
      envFrom:
        - configMapRef:
            name: sample
---
apiVersion: v1
kind: Secret
metadata:
  name: sample
data:
  USERNAME: YWRtaW4=
  PASSWORD: YWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: demo6
spec:
  containers:
    - name: centos
      image: centos:7
      command: [ "sleep", "10000" ]
      envFrom:
        - configMapRef:
            name: sample
        - secretRef:
            name: sample
