apiVersion: v1
kind: Pod
metadata:
  name: demo2
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: demo3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: mongodb
      image: mongo
