apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.16

---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: frontend-deploy
#spec:
#  # modify replicas according to your case
#  replicas: 2
#  selector:
#    matchLabels:
#      tier: frontend-deploy
#  template:
#    metadata:
#      labels:
#        tier: frontend-deploy
#    spec:
#      containers:
#      - name: nginx
#        image: nginx:1.17
---
apiVersion: v1
kind: Pod
metadata:
  name: demo2
  labels:
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80