apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: guestbook
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: httpd
        image: httpd

---
apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: httpd.devopsb61.online
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd
          servicePort: 80
